[buildPlans.fission]
export-glyph-names = true
family = "Fission"
serifs = "slab"
spacing = "fontconfig-mono"

[buildPlans.fission.variants.design]
a = "double-storey-tailed"
ampersand = "closed"
at = "fourfold"
bar = "force-upright"
c = "unilateral-serifed"
capital-a = "curly-base-serifed"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-g = "toothed-inward-serifed-hooked"
capital-gamma = "serifed"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-m = "hanging-motion-serifed"
capital-r = "curly"
capital-v = "curly"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "straight-serifed-with-horizontal-crossbar"
cyrl-capital-ka = "straight-serifless"
cyrl-capital-u = "cursive"
cyrl-capital-ya = "standing-open"
cyrl-capital-ze = "unilateral-serifed"
cyrl-che = "standard"
cyrl-ef = "serifed"
cyrl-el = "straight"
cyrl-en = "serifless"
cyrl-ka = "straight-serifless"
cyrl-ya = "standing-open-tailed"
cyrl-yeri = "round"
cyrl-yery = "round-tailed"
cyrl-ze = "unilateral-serifed"
d = "tailed-serifed"
dollar = "through"
e = "flat-crossbar"
eight = "two-circles"
eszet = "sulzbacher"
f = "serifed"
four = "semi-open-non-crossing"
g = "single-storey-flat-hook-serifless"
i = "serifed"
k = "symmetric-connected-serifed"
l = "serifed"
lig-ltgteq = "flat"
long-s = "flat-hook-tailed"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight-turn"
m = "short-leg"
r = "serifed"
s = "bilateral-serifed"
three = "flattop"
turn-v = "straight"
u = "motion-serifed"
v = "curly"
w = "straight"
x = "curly-serifed"
y = "curly-turn"
z = "straight-serifed-with-horizontal-crossbar"

[buildPlans.fission.ligations]
inherits = "javascript"

[buildPlans.fission.exclude-chars]
ranges = [[0x23FB, 0x23FE], [0x2665, 0x2665], [0x26A1, 0x26A1], [0x2B58, 0x2B58], [0xE000, 0xE00D], [0xE0A3, 0xE0A3], [0xE0B4, 0xE0C8], [0xE0CA, 0xE0CA], [0xE0CC, 0xE0D2], [0xE0D4, 0xE0D4], [0xE200, 0xE2A9], [0xE300, 0xE3EB], [0xE5FA, 0xE62B], [0xE700, 0xE7C5], [0xF000, 0xF2E0], [0xF27C, 0xF27C], [0xF300, 0xF313], [0xF400, 0xF4A8], [0xF500, 0xFD46]]
